export const headerData = [
    { title: "Home", href: "/" },
    { title: "Shop", href: "/shop" },
    { title: "Categories", href: "/categories" },
    { title: "Blog", href: "/blog" },
    { title: "Hot Deal", href: "/deal" },
];

export const quickLinksData = [
    { title: "About us", href: "/about" },
    { title: "Contact us", href: "/contact" },
    { title: "Terms & Conditions", href: "/terms" },
    { title: "Privacy Policy", href: "/privacy" },
    { title: "FAQs", href: "/faqs" },
    { title: "Help", href: "/help" },
];

export const categoriesData = [
    { title: "Mobiles", href: "mobiles" },
    { title: "Appliances", href: "appliances" },
    { title: "Smartphones", href: "smartphones" },
    { title: "Air Conditioners", href: "air-conditioners" },
    { title: "Washing Machine", href: "washing-machine" },
    { title: "Kitchen Appliances", href: "kitchen-appliances" },
    { title: "Gadget Accessories", href: "gadget-accessories" },
];

export const productType = [
    { title: "Gadget", value: "gadget" },
    { title: "Appliances", value: "appliances" },
    { title: "Refrigerators", value: "refrigerators" },
    { title: "Others", value: "others" },
];

/** Sample products — replace with real API/DB data when backend is ready */
export const sampleProducts = [
    {
        id: "1",
        title: "JBL E55BT Wireless Bluetooth Headphones",
        category: "Airbuds",
        buyPrice: 155.0,
        price: 259.0,
        originalPrice: 284.9,
        rating: 4,
        reviews: 5,
        stock: 30,
        isSale: true,
        isHot: false,
        image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "2",
        title: "MacBook Pro M4 Max Chip 16-inch",
        category: "Gadget Accessories",
        buyPrice: 2799.0,
        price: 3999.0,
        originalPrice: 4278.93,
        rating: 5,
        reviews: 5,
        stock: 35,
        isSale: false,
        isHot: true,
        image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "3",
        title: "Mpow CHE2S On-Ear Headphones",
        category: "Gadget Accessories",
        buyPrice: 330.0,
        price: 550.0,
        originalPrice: 605.0,
        rating: 4,
        reviews: 5,
        stock: 60,
        isSale: false,
        isHot: true,
        image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "4",
        title: "Realme Note 60x (4/64GB)",
        category: "Gadget Accessories, Smartphones",
        buyPrice: 489.0,
        price: 699.0,
        originalPrice: 768.9,
        rating: 4,
        reviews: 5,
        stock: 9,
        isSale: true,
        isHot: false,
        image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "5",
        title: "Samsung Galaxy S25 Ultra 5G",
        category: "Gadget Accessories, Smartphones",
        buyPrice: 1161.0,
        price: 1659.0,
        originalPrice: 1907.85,
        rating: 5,
        reviews: 5,
        stock: 99,
        isSale: false,
        isHot: true,
        image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "6",
        title: "Sony WH-1000XM5 Noise Cancelling",
        category: "Airbuds",
        buyPrice: 244.99,
        price: 349.99,
        originalPrice: 399.99,
        rating: 5,
        reviews: 12,
        stock: 18,
        isSale: true,
        isHot: false,
        image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "7",
        title: "JBL Clip 4 Portable Speaker",
        category: "Gadget Accessories",
        buyPrice: 47.97,
        price: 79.95,
        originalPrice: null,
        rating: 4,
        reviews: 8,
        stock: 45,
        isSale: false,
        isHot: true,
        image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "8",
        title: "Apple AirPods Pro 2nd Generation",
        category: "Airbuds",
        buyPrice: 174.0,
        price: 249.0,
        originalPrice: 279.0,
        rating: 5,
        reviews: 32,
        stock: 14,
        isSale: true,
        isHot: true,
        image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "9",
        title: "USB-C Fast Charger 65W GaN",
        category: "Gadget Accessories",
        buyPrice: 14.99,
        price: 24.99,
        originalPrice: 34.99,
        rating: 4,
        reviews: 210,
        stock: 50,
        isSale: true,
        isHot: false,
        image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?q=80&w=800&auto=format&fit=crop",
    },
    {
        id: "10",
        title: "iPad Air M2 11-inch WiFi 256GB",
        category: "Gadget Accessories",
        buyPrice: 599.0,
        price: 799.0,
        originalPrice: 899.0,
        rating: 5,
        reviews: 15,
        stock: 22,
        isSale: false,
        isHot: true,
        image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop",
    },
];
